// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_A46qSy-gDHx6lHrkm8QWaixxFVDjjU',
    appId: '1:371745891018:web:23a9a2c316c5ec0e88ca33',
    messagingSenderId: '371745891018',
    projectId: 'school-e04b8',
    authDomain: 'school-e04b8.firebaseapp.com',
    storageBucket: 'school-e04b8.firebasestorage.app',
    measurementId: 'G-WR6VHEED9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7XmDYOuQsHS0obhS3WW1ZmtPmq8pD-E',
    appId: '1:371745891018:android:f7f82bbd0a559a6788ca33',
    messagingSenderId: '371745891018',
    projectId: 'school-e04b8',
    storageBucket: 'school-e04b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCikqidxUUGWVuUJ2qnyx-19inxkwPxd-o',
    appId: '1:371745891018:ios:c5354e68a2b6551388ca33',
    messagingSenderId: '371745891018',
    projectId: 'school-e04b8',
    storageBucket: 'school-e04b8.firebasestorage.app',
    iosBundleId: 'com.schoolmanagement.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCikqidxUUGWVuUJ2qnyx-19inxkwPxd-o',
    appId: '1:371745891018:ios:c5354e68a2b6551388ca33',
    messagingSenderId: '371745891018',
    projectId: 'school-e04b8',
    storageBucket: 'school-e04b8.firebasestorage.app',
    iosBundleId: 'com.schoolmanagement.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_A46qSy-gDHx6lHrkm8QWaixxFVDjjU',
    appId: '1:371745891018:web:c05ffd764f02899688ca33',
    messagingSenderId: '371745891018',
    projectId: 'school-e04b8',
    authDomain: 'school-e04b8.firebaseapp.com',
    storageBucket: 'school-e04b8.firebasestorage.app',
    measurementId: 'G-PHPHR8M6DZ',
  );
}
